version: "3"

services:
  app:
    build: .
    working_dir: /workspace
    volumes:
      - .:/workspace:delegated
    ports:
      - "3000:3000" # client
      - "5000:5000" # server
    stdin_open: true
    tty: true